Repository Skatteetaten/terraform-nomad-hive, pull requests merged in 2020-11, with the labels that each got.

#46 Bump vagrant-hashistack ver 0.6.1 ~> 0.7.1
  CHANGELOG.md
  Vagrantfile.default
  dev/vagrant/bootstrap/nomad/post/030-update-nomad-write-default-policy.yml
  example/standalone/providers.tf
Labels: type/enhancement

#55 Add sidecar in metastore-proxy resolves #54
  CHANGELOG.md
  README.md
  conf/nomad/hive.hcl
  example/standalone/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#53 Creds management
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/hive.hcl
  dev/ansible/01_generate_secrets_vault.yml
  dev/ansible/05_build_docker_image.yml
  dev/ansible/10_run_terraform.yml
  dev/ansible/15_healthcheck_test.yml
  dev/ansible/20_upload_files.yml
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
  dev/vagrant/conf/nomad/00-enable_vault.hcl
  example/README.md
  example/standalone-user-provided-creds/README.md
  example/standalone-user-provided-creds/main.tf
  example/standalone-user-provided-creds/providers.tf
  example/standalone-user-provided-creds/variables.tf
  example/standalone-vault-provided-creds/README.md
  example/standalone-vault-provided-creds/main.tf
  example/standalone-vault-provided-creds/providers.tf
  example/standalone-vault-provided-creds/variables.tf
  example/standalone/README.md
  main.tf
  outputs.tf
  variables.tf
Labels: type/enhancement

#56 Release 0.3.0
  CHANGELOG.md
Labels: minor

#58 Add minio health check
  CHANGELOG.md
  conf/nomad/hive.hcl
  dev/ansible/15_healthcheck_test.yml
Labels: type/enhancement

#61 Release 0.3.1
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
Labels: patch
