Repository Skatteetaten/terraform-nomad-hive, pull requests merged in 2020-10, with the labels that each got.

#23 Issue 20 and 3 - bump versions minio postgres and added documentation
  CHANGELOG.md
  README.md
  example/main.tf
Labels: documentation, enhancement

#25 Release 0.1.0
  CHANGELOG.md
Labels: minor

#30 Adding github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: theme/ci

#32 Update box ~> 0.6.1
  Vagrantfile.default
  dev/ansible/00_create_intention.yml
  example/nomad_acl_test.tf
  example/providers.tf
  template_example/.env
  template_example/Vagrantfile
  template_example/conf/nomad/countdash.hcl
  template_example/dev/ansible/01_build_docker_image.yml
  template_example/dev/ansible/02_run_terraform.yml
  template_example/dev/ansible/playbook.yml
  template_example/dev/vagrant/conf/consul/99-override.hcl
  template_example/dev/vagrant/conf/nomad/99-override.hcl
  template_example/dev/vagrant/conf/post_ansible.sh
  template_example/dev/vagrant/conf/post_bootstrap/00-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/01-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/02-poststart-example.yml
  template_example/dev/vagrant/conf/pre_ansible.sh
  template_example/dev/vagrant/conf/pre_bootstrap/00-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/01-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/02-prestart-example.yml
  template_example/dev/vagrant/conf/vault/99-override.hcl
  template_example/docker/.dockerignore
  template_example/docker/Dockerfile
  template_example/docker/conf/certificates/.gitignore
  template_example/docker/conf/certificates/README.md
  template_example/example/standalone/main.tf
  template_example/example/standalone/variables.tf
  template_example/main.tf
  template_example/outputs.tf
  template_example/variables.tf
Labels: type/enhancement

#33 Sync with original template
  .github/action/find-replace.py
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  Makefile
  Vagrantfile.default
  dev/vagrant/bootstrap/README.md
  dev/vagrant/conf/README.md
  dev/vagrant/conf/post_bootstrap/README.md
  format.sh
  versions.tf
Labels: type/enhancement

#35 conditional rendering
  CHANGELOG.md
  README.md
  conf/nomad/hive.hcl
  conf/nomad/hive_local.hcl
  dev/ansible/01_build_docker_image.yml
  example/main.tf
  main.tf
  variables.tf
Labels: type/documentation, type/enhancement

#36 Add canary add canary switch
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/hive.hcl
  example/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#38 Extract resource alloc in variables
  CHANGELOG.md
  README.md
  conf/nomad/hive.hcl
  example/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#39 Add data example upload
  CHANGELOG.md
  README.md
  dev/ansible/00_create_intention.yml
  dev/ansible/04_upload_files.yml
  example/resources/data/csv/iris.csv
  example/vagrant_box_example/README.md
  example/vagrant_box_example/main.tf
  example/vagrant_box_example/nomad_acl.tf
Labels: type/documentation, type/enhancement

#40 Update dependent modules (bump versions)
  CHANGELOG.md
  README.md
  dev/ansible/02_run_terraform.yml
  dev/ansible/04_upload_files.yml
  dev/vagrant/bootstrap/nomad/post/030-update-nomad-write-default-policy.yml
  dev/vagrant/bootstrap/nomad/post/host_volume_policy.hcl
  dev/vagrant/bootstrap/nomad/pre/00-create_dir_for_persisting_data.yml
  dev/vagrant/conf/nomad/99-mount-host-volume.hcl
  example/README.md
  example/standalone/README.md
  example/standalone/main.tf
  example/standalone/providers.tf
  example/standalone/resources/data/csv/iris.csv
  example/standalone/variables.tf
Labels: type/enhancement

#41 Release 0.2.0
  CHANGELOG.md
Labels: minor, type/enhancement

#43 Add intentions doc
  CHANGELOG.md
  README.md
  dev/ansible/04_upload_files.yml
  example/README.md
  example/resources/data/csv/iris.csv
Labels: type/documentation
