Repository Skatteetaten/terraform-nomad-hive, pull requests merged in 2021-04, with the labels that each got.

#81 Updated links/urls in readmes
  CHANGELOG.md
  README.md
  dev/vagrant/bootstrap/README.md
  example/standalone-user-provided-creds/README.md
  example/standalone-vault-provided-creds/README.md
Labels: priority/medium, stage/ready, type/documentation

#84 Add hive-minio-availability healthcheck
  CHANGELOG.md
  conf/nomad/hive.hcl
Labels: type/enhancement

#85 Release 0.4.1
  CHANGELOG.md
Labels: patch
